# Generated by Django 4.1.6 on 2023-02-23 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxology", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taxon",
            name="remarks",
            field=models.TextField(blank=True, null=True),
        ),
    ]
